KEYWORDS = [

    "how volcanic eruptions shape the earth's surface",
    "ancient cities that disappeared without a trace",
    "why some animals can survive extreme temperatures",
    "how deep sea creatures survive without sunlight",
    "most unusual architectural structures around the world",
    "mysterious archaeological discoveries that changed history",
    "how airplanes stay in the air explained simply",
    "why oceans have different shades of blue",
    "strange weather phenomena recorded around the world",
    "how satellites communicate with earth from space",
    "forgotten inventions that were ahead of their time",
    "how ancient civilizations measured time",
    "why certain places experience midnight sun",
    "how earthquakes are detected before major damage",
    "most fascinating abandoned places around the world",
    "how glaciers shape mountains and valleys",
    "why some metals change color over time",
    "how black holes affect nearby objects",
    "unsolved mysteries from ancient history",
    "how coral reefs support entire marine ecosystems",
    "why deserts can become extremely cold at night",
    "how ancient people navigated without modern maps",
    "rare natural phenomena that happen only in certain regions",
    "how fossils reveal information about prehistoric life",
    "why lightning can create unusual glass formations",
    "how caves form deep beneath the ground",
    "strange traditions from different cultures around the world",
    "how bridges are designed to withstand strong winds",
    "why some lakes have naturally unusual colors",
    "how astronomers discover planets outside our solar system",
    "historical technologies that are still used today",
    "how migratory birds navigate thousands of kilometers",
    "why certain mountains have permanent snow",
    "how ancient civilizations built massive stone structures",
    "scientific discoveries that happened completely by accident",
]