KEYWORDS = [
    "beginner guide to building a personal website from scratch",
    "how to choose the right laptop for remote work",
    "creative ways to decorate a small apartment",
    "best indoor plants for low light rooms",
    "how to start learning a new language effectively",
    "simple photography techniques for better smartphone photos",
    "how to create a professional resume with no experience",
    "beginner friendly woodworking projects for weekends",
    "how to organize digital files on your computer",
    "best books to read when starting a business",
    "how to make a small bedroom look more spacious",
    "practical ways to reduce household electricity usage",
    "beginner guide to understanding cryptocurrency wallets",
    "how to start a profitable online store from home",
    "easy coffee brewing methods to try at home",
    "how to improve public speaking skills for beginners",
    "creative birthday gift ideas for close friends",
    "how to build a capsule wardrobe on a budget",
    "beginner guide to caring for aquarium fish",
    "how to create a monthly household budget spreadsheet",
    "best creative hobbies to learn at home",
    "how to prepare for your first job interview",
    "simple ways to make homemade candles",
    "how to start journaling without overthinking it",
    "beginner guide to investing in index funds",
    "how to make restaurant style pasta at home",
    "best board games for small groups of friends",
    "how to declutter your home one room at a time",
    "creative ways to repurpose old clothes",
    "how to protect important files from computer failure",
    "beginner tips for learning graphic design",
    "how to plan a memorable low budget birthday party",
    "interesting science experiments you can do at home",
    "how to build a simple personal knowledge management system",
    "unique weekend projects that teach useful practical skills",
]